services:
  api:
    build: .
    container_name: residents-management_api
    ports:
      - "3000:3000"
    env_file:
      - .env  # local dev
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: residents-management_postgres
    restart: always
    environment:
      POSTGRES_USER: residents
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: residents-management
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
